---
title: "IOH and dengue supplementary figures"
author: "Alyson Singleton"
date: "`r Sys.Date()`"
output:
  html_document: default
  word_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# install packages, load libraries, set themes, knit formatting
pacman::p_load(tidyverse, dplyr, kableExtra, knitr, sf, raster, terra, spData, tmap, leaflet, ggplot2, spThin, mapdata, rnaturalearth, rnaturalearthdata, devtools, mapview, grid, gridExtra, RColorBrewer, raster, plm, fixest, cobalt, broom, ggpubr, gridExtra, cowplot, ggspatial, directlabels, scales, ggrepel, patchwork, readxl) #brazilmaps

theme_set(theme_minimal())

knitr::opts_chunk$set(echo = F, results='asis', warning=F, message=F, cache=F,
                      fig.height=5, fig.width=10)

get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

library(showtext)
font_add("Arial", "/Library/Fonts/Arial.ttf")  # Use the actual file path
showtext_auto()

theme_stor <- theme(panel.grid.minor.x = element_line(linewidth = 0.3),
                    panel.grid.major.x = element_line(linewidth = 0.3),
                    panel.grid.major.y = element_line(linewidth = 0.3),
                    axis.line.x = element_line(color = "black", linewidth = 0.3),
                    axis.line.y = element_line(color = "black", linewidth = 0.3),
                    plot.title = element_text(size=20, hjust=0.1),
                    plot.title.position = "plot",
                    plot.subtitle = element_text(hjust=0.5, size=22),
                    axis.title=element_text(size=12),
                    axis.title.y=element_text(size=11,angle=0, vjust=.5, hjust=0.5),
                    axis.text.y=element_text(size=12),
                    axis.title.x=element_text(size=12),
                    axis.text.x=element_text(size=12),
                    #axis.text = element_text(size=14),
                    legend.text=element_text(size=12),
                    legend.title=element_text(size=12),
                    legend.position = "none",
                    strip.text.x = element_text(size = 12))
```

```{r, STable1}
#####################
## STable 1
#####################
stable1 <- etable(dengue_yearly_model, leish_yearly_model, 
                  digits = 3,
                  signif.code = c("*" = 0.05))
stable1 <- stable1[c(3:10,37,11:31,35,34,36),2:3]
stable1[33,] <- c(rep(length(unique(dengue_yearly$connected_buffered$key)),2))
stable1[9,] <- c("----","----")
colnames(stable1) <- c('Dengue Yearly', 'Leish Yearly')
rownames(stable1) <- c("5km x 2000", "5km x 2001", "5km x 2002", "5km x 2003", "5km x 2004", "5km x 2005", "5km x 2006", "5km x 2007", "5km x 2008", "5km x 2009", "5km x 2010", "5km x 2011", "5km x 2012", "5km x 2013", "5km x 2014", "5km x 2015", "5km x 2016", "5km x 2017", "5km x 2018", "5km x 2019", "5km x 2020", "5km x 2021", "5km x 2022", "Urban", "Agriculture", "Precipitation", "Temperature^2", "FEs", "Unit", "Year", "R^2", "N", "Units")
stable1[] <- lapply(stable1, function(col) {
  ifelse(col == "Yes", "X", ifelse(col == "No", "", col))
})
stable1[31,] <- round(as.numeric(stable1[31,]),3)
stable1
write.csv(stable1, "~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/stable1.csv")
```

```{r, STable2}
#####################
## STable S2
#####################
stable2 <- etable(dengue_ld_model_main,dengue_ld_model_no_PM,
                  dengue_ld_model_no_land_use,dengue_ld_model_pop_weight,
                  dengue_ld_model_onekm,dengue_ld_model_tenkm,
                  dengue_ld_model_no_buffer,dengue_ld_model_buffer_bigger,
                  dengue_ld_model_cp,dengue_ld_model_w_dengue, 
                  digits = 3,
                  signif.code = c("*" = 0.05))
stable2 <- stable2[c(3:9,16,15,14),2:11]
stable2[10,] <- (as.numeric(gsub(",","",stable2[9,])))/15
colnames(stable2) <- c('Main model', 'No PM', 'No LUC', 'Pop weight','1km boundary','10km boundary','No buffer (<5km v >5km)', 'Large buffer (<5km v >20km)', 'Conf & prob cases', 'Units w dengue')
rownames(stable2) <- c("Urban", "Agriculture", "Precipitation", "Temperature^2", "5km x Post-2008", "1km x Post-2008", "10km x Post-2008", "R^2", "N", "Units")
stable2 <- stable2[c(5:7,1:4, 8:10),]
stable2[8,] <- round(as.numeric(stable2[8,]),3)
stable2
write.csv(stable2, "~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/stable2.csv")
```

```{r, STable3}
#####################
## STable 3
#####################
stable3 <- etable(dengue_yearly_ld_model_quad,dengue_biannual_ld_model_dry_quad,dengue_biannual_ld_model_rainy_quad, 
                 leish_yearly_ld_model_quad,leish_biannual_ld_model_dry_quad,leish_biannual_ld_model_rainy_quad, 
                 digits = 3,
                 signif.code = c("*" = 0.05))
stable3 <- stable3[c(3:8,9:12,16,15,14),2:7]
stable3[13,] <- c(rep(length(unique(dengue_yearly$connected_buffered$key)),6))
colnames(stable3) <- c('Dengue Yearly', 'Dengue Biannual Dry', 'Dengue Biannual Rainy','Leish Yearly','Leish Biannual Dry', 'Leish Biannual Rainy')
rownames(stable3) <- c("Urban", "Agriculture", "Precipitation^2", "Temperature^2", "5km x Post-2008 Yearly", "5km x Post-2008 Biannual", "FEs", "Unit", "Year", "Biannual", "R^2", "N", "Units")
stable3 <- stable3[c(5:6,1:4,7:13),]
stable3[] <- lapply(stable3, function(col) {
  ifelse(col == "Yes", "X", ifelse(col == "No", "", col))
})
stable3[11,] <- round(as.numeric(stable3[11,]),3)
stable3
write.csv(stable3, "~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/stable3.csv")
```

```{r, STable4}
#####################
## STable 4
#####################
## load from gee
cost_mapping <- read.csv("~/Desktop/doctorate/ch2 mdd highway/data/cost_mapping.csv")

## load linked e_salud codes and cluster ids & link
linked_ids_codes <- read.csv("~/Desktop/doctorate/ch2 mdd highway/data/key_esalud_clusterid_7.5km.csv")
cost_mapping_linked <- full_join(linked_ids_codes, cost_mapping, by = 'key')
cost_mapping_linked <- cost_mapping_linked %>%
  dplyr::select("key", "latitude", "longitude", "clust", "cumulative_cost", ".geo")

## load distance boundary vars and link
boundary_dummy_vars <- read.csv("~/Desktop/doctorate/ch2 mdd highway/data/boundary_dummy_vars_0km/boundary_dummy_vars_0km.csv")
cost_mapping_linked_buffers <- left_join(cost_mapping_linked, boundary_dummy_vars, by='key')
cost_mapping_linked_buffers <- cost_mapping_linked_buffers %>%
  mutate(all_cutoffs = if_else(all_cutoffs == 7, 6, all_cutoffs)) %>%
  group_by(all_cutoffs) %>%
  summarize(cumulative_cost_mean_minutes = median(cumulative_cost, na.rm=T)) %>%
  mutate(cumulative_cost_mean_hours = cumulative_cost_mean_minutes/60)

#prep for nice export
stable4 <- cost_mapping_linked_buffers %>%
  mutate(distance_label = case_when(
  all_cutoffs == 1 ~ '1km',
  all_cutoffs == 2 ~ '5km',
  all_cutoffs == 3 ~ '10km',
  all_cutoffs == 4 ~ '15km',
  all_cutoffs == 5 ~ '20km',
  all_cutoffs == 6 ~ '40km',
  all_cutoffs == 0 ~ '>40km')) %>%
  mutate(distance_label = factor(distance_label, levels = c('1km', '5km', '10km', '15km', '20km', '40km', '>40km'))) %>%
  arrange(distance_label) %>%
  mutate(cumulative_cost_mean_minutes = round(cumulative_cost_mean_minutes)) %>%
  rename(`Median Travel Time to Interoceanic Highway (min)` = cumulative_cost_mean_minutes,
    `Distance Boundary` = distance_label) %>%
  dplyr::select(`Distance Boundary`, `Median Travel Time to Interoceanic Highway (min)`)
  
stable4

write.csv(stable4, "~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/stable4.csv")
```

```{r, STable5}
#####################
## STable 5
#####################

# Extract fixed effects from both models
fe_vals_dengue <- fixef(dengue_yearly_agg_model)
fe_vals_leish <- fixef(leish_yearly_agg_model)

# Create labeled tibble for dengue
fe_df_dengue <- bind_rows(
  tibble(unit = names(fe_vals_dengue$key), effect_dengue = fe_vals_dengue$key, fixed_effect = "key"),
  tibble(unit = names(fe_vals_dengue$year), effect_dengue = fe_vals_dengue$year, fixed_effect = "year")
) %>%
  mutate(
    fe_label = case_when(
      fixed_effect == "key"  ~ paste0("Unit FE: ", unit),
      fixed_effect == "year" ~ paste0("Year FE: ", unit)
    )
  )

# Create labeled tibble for leishmaniasis
fe_df_leish <- bind_rows(
  tibble(unit = names(fe_vals_leish$key), effect_leish = fe_vals_leish$key, fixed_effect = "key"),
  tibble(unit = names(fe_vals_leish$year), effect_leish = fe_vals_leish$year, fixed_effect = "year")
) %>%
  mutate(
    fe_label = case_when(
      fixed_effect == "key"  ~ paste0("Unit FE: ", unit),
      fixed_effect == "year" ~ paste0("Year FE: ", unit)
    )
  ) %>%
  dplyr::select(fe_label, effect_leish)

# Join dengue and leish fixed effects by label
stable5 <- fe_df_dengue %>%
  left_join(fe_df_leish, by = "fe_label") %>%
  dplyr::select(Term = fe_label, Dengue_FE = effect_dengue, Leish_FE = effect_leish)

colnames(stable5) <- c("Term", "Dengue Intercept", "Leish Intercept")
stable5[,c(2:3)] <- round(stable5[,c(2:3)], 2)

# Export
write.csv(stable5, "~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/stable5.csv")
```

```{r, STable6}
#####################
## STable 6
#####################
stable6 <- etable_glmmTMB[,c(2:7)]
colnames(stable6) <- c('Dengue Yearly', 'Dengue Biannual Dry', 'Dengue Biannual Rainy','Leish Yearly','Leish Biannual Dry', 'Leish Biannual Rainy')
stable6 <- as.data.frame(rbind(stable6, stable3[c(7:10),]))
stable6 <- stable6 %>%
  mutate(across(everything(), ~ ifelse(is.na(.), "", .)))
rownames(stable6) <- c("5km x Post-2008 Yearly", "5km x Post-2008 Biannual", "Urban", "Agriculture", "Precipitation", "Temperature^2", "FEs", "Unit", "Year", "Biannual")
stable6
write.csv(stable6, "~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/stable6.csv")
```

```{r, STable7}
#####################
## STable 7
#####################

coefs <- summary(dengue_yearly_model_glmmTMB)$coefficients$cond

dengue_yearly_df_full <- as.data.frame(coefs) %>%
  rownames_to_column("term") %>%
  rename(
    estimate = Estimate,
    std_error = `Std. Error`,
    z_value = `z value`,
    p_value = `Pr(>|z|)`
  ) %>%
  mutate(
    star = if_else(p_value < 0.05, "*", ""),
    formatted = sprintf("%.2f%s (%.2f)", estimate, star, std_error),
    term_clean = case_when(
      grepl("factor\\(key\\)", term) ~ gsub("factor\\(key\\)", "Unit FE: ", term),
      grepl("factor\\(year\\)", term) ~ gsub("factor\\(year\\)", "Year FE: ", term),
      TRUE ~ term
    )
  )%>%
  mutate(formatted = ifelse(is.na(estimate), "Dropped (collinear)", 
                            sprintf("%.2f%s (%.2f)", estimate, star, std_error)))

# --- Optional: move main variables to the top ---
main_vars <- c("(Intercept)", "year_binary:fivekm", "year_binary", "fivekm", "sum_precip", "mean_temp", "urban", "ag")
dengue_yearly_df_full <- dengue_yearly_df_full %>%
  mutate(
    term_rank = match(term, main_vars),
    key_num = ifelse(grepl("^Unit FE: ", term_clean),
                     as.numeric(gsub("Unit FE: ", "", term_clean)),
                     NA),
    year_str = ifelse(grepl("^Year FE: ", term_clean),
                      term_clean,
                      NA)
  ) %>%
  arrange(
    is.na(term_rank), term_rank,          # Main vars first
    is.na(key_num), key_num,              # Then order Key FEs numerically
    year_str                              # Then Year FEs alphabetically
  )

# --- Final clean table ---
stable7 <- dengue_yearly_df_full %>%
  dplyr::select(Term = term_clean, `Estimate (SE)` = formatted)
stable7 <- stable7[c(1,2,4,3,7,8,5,6,9:101),]
stable7[2:8,1] <- c("5km x Post-2008 Yearly", "5km", "Post-2008 Yearly", "Urban", "Agriculture", "Sum Precipitation", "Temperature^2")
stable7

write.csv(stable7, "~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/stable7.csv")

```

```{r, SFig S1}
#####################
## SFig 1a
#####################
dengue_yearly$full$case_yn <- ifelse(dengue_yearly$full$yearly_cases>0, 1, 0)
dengue_coverage_yearly <- dengue_yearly$full %>%
  group_by(year, fivekm) %>%
  summarize(coverage = sum(case_yn))

dengue_coverage_yearly$fivekm <- as.character(dengue_coverage_yearly$fivekm)
dengue_coverage_yearly$year <- format(as.Date(dengue_coverage_yearly$year, format="%Y-%m-%d"),"%Y")

sfig1a <- ggplot(dengue_coverage_yearly) +
  geom_col(aes(x= year, y=coverage, fill=fivekm), width=0.5, color="white", position = position_dodge(width = 0.5)) +
  scale_fill_manual(name = "", values=c('#648FFF', '#E04490'), labels=c('>5km', '<5km'),) +
  geom_vline(aes(xintercept=("2008")), linetype='dashed', size=0.4) +
  xlab("") + ylab("# units w/\ndengue\ncase") + 
  theme_bw()+
  theme(plot.title = element_text(hjust=0.5, size=26, face="italic"),
        plot.subtitle = element_text(hjust=0.5, size=22),
        axis.title.y=element_text(size=12,angle=0, vjust=.5, hjust=0.5),
        axis.text.y=element_text(size=10),
        axis.title.x=element_text(size=10),
        axis.text.x=element_text(size=10, angle=45, vjust=0.45),
        axis.text = element_text(size=16),
        legend.text=element_text(size=12),
        legend.title=element_text(size=12),
        legend.position = "bottom",
        strip.text.x = element_text(size = 14))
sfig1a
sfig1_legend <- get_legend(sfig1a)
sfig1a <- sfig1a + theme(legend.position = "none")

#####################
## SFig 1b
#####################
leish_yearly$full$case_yn <- ifelse(leish_yearly$full$yearly_cases>0, 1, 0)
leish_coverage_yearly <- leish_yearly$full %>%
  group_by(year, fivekm) %>%
  summarize(coverage = sum(case_yn))

leish_coverage_yearly$fivekm <- as.character(leish_coverage_yearly$fivekm)
leish_coverage_yearly$year <- format(as.Date(leish_coverage_yearly$year, format="%Y-%m-%d"),"%Y")

sfig1b <- ggplot(leish_coverage_yearly) +
  geom_col(aes(x= year, y=coverage, fill=fivekm), color="white", width=0.5, position = position_dodge(width = 0.5)) +
  scale_fill_manual(name = "Treatment", values=c('#648FFF', '#E04490'), labels=c('>5km', '<5km'),) +
  geom_vline(aes(xintercept=("2008")), linetype='dashed', size=0.4) +
  xlab("Year") + ylab("# units w/\nleish\ncase") + 
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5, size=26, face="italic"),
        plot.subtitle = element_text(hjust=0.5, size=22),
        axis.title.y=element_text(size=12, angle=0, vjust=.5, hjust=0.5),
        axis.text.y=element_text(size=10),
        axis.title.x=element_text(size=12),
        axis.text.x=element_text(size=10, angle=45, vjust=0.45),
        axis.text = element_text(size=16),
        legend.text=element_text(size=14),
        legend.title=element_text(size=14),
        legend.position = "none",
        strip.text.x = element_text(size = 14))
sfig1b

#####################
## SFig 1all
#####################

sfig1all <- grid.arrange(sfig1a, sfig1b, sfig1_legend,
                         ncol = 1, nrow = 3,
                         layout_matrix = rbind(c(1),c(2),c(3)), 
                         heights=c(3,3,1))

sfig1all <- as_ggplot(sfig1all) +                                
  draw_plot_label(label = c("A", "B"), size = 14,
                  x = c(0.133, 0.133), y = c(0.99, 0.56)) 
sfig1all

ggsave("SFig1.pdf", plot=sfig1all, path="~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/", width = 8, height = 7, units="in", device = "pdf")

```

```{r, SFig S2}
## SFig S2 in 06_sfig_s2.R file
```

```{r, SFig S3}
#####################
## SFig 3
#####################

#load supplementary model results
sfig3_df <- rbind(
  as.data.frame(cbind(dengue_yearly_model_no_PM$coeftable[1:22,],c(rep("No PM",22)))),
  as.data.frame(cbind(dengue_yearly_model_no_land_use$coeftable[1:22,],c(rep("No LUC",22)))),
  as.data.frame(cbind(dengue_yearly_model_pop_weight$coeftable[1:22,],c(rep("Pop weight",22)))),
  as.data.frame(cbind(dengue_yearly_model_onekm$coeftable[1:22,],c(rep("1km",22)))),
  as.data.frame(cbind(dengue_yearly_model_tenkm$coeftable[1:22,],c(rep("10km",22)))),
  as.data.frame(cbind(dengue_yearly_model_no_buffer$coeftable[1:22,],c(rep("No buffer",22)))),
  as.data.frame(cbind(dengue_yearly_model_buffer_bigger$coeftable[1:22,],c(rep("Big buffer",22)))),
  as.data.frame(cbind(dengue_yearly_model_cp$coeftable[1:22,],c(rep("Conf & prob cases",22)))),
  as.data.frame(cbind(dengue_yearly_model_w_dengue$coeftable[1:22,],c(rep("Units w dengue",22)))),
  as.data.frame(cbind(dengue_yearly_model_main$coeftable[1:22,],c(rep("Main",22)))))

colnames(sfig3_df) <- c('estimate', 'std_error', 't_value', 'p_value', 'Model')
sfig3_df$year <- c(seq(as.Date("2000-01-01"), as.Date("2007-01-01"), by="year"),
                   seq(as.Date("2009-01-01"), as.Date("2022-01-01"), by="year"))
sfig3_df$estimate <- as.numeric(sfig3_df$estimate)
sfig3_df$std_error <- as.numeric(sfig3_df$std_error)
sfig3_df$upper <- sfig3_df$estimate+1.96*sfig3_df$std_error
sfig3_df$lower <- sfig3_df$estimate-1.96*sfig3_df$std_error
sfig3_df$Model <- factor(as.character(sfig3_df$Model), levels=c('No PM', 'No LUC', 'Pop weight','1km','10km','No buffer', 'Big buffer', 'Conf & prob cases', "Units w dengue", 'Main'))

main_df <- sfig3_df %>% filter(Model == "Main")

# Get list of other models
other_models <- levels(sfig3_df$Model)[levels(sfig3_df$Model) != "Main"]

# For each other model, bind with Main and assign a facet group
facet_df <- lapply(other_models, function(mod) {
  bind_rows(main_df, sfig3_df %>% 
              filter(Model == mod)) %>% 
    mutate(Facet = mod)
}) %>% 
  bind_rows()

facet_df$Facet <- factor(facet_df$Facet, levels = c('No PM', 'No LUC', 'Pop weight','1km','10km',
                                                    'No buffer', 'Big buffer', 'Conf & prob cases', 'Units w dengue'))

facet_labels <- setNames(paste0(LETTERS[1:9], ") ", c('No Puerto Maldonado', 'No land-use covariates', 'Population weighting','1km boundary','10km boundary',
                                                      'No buffer (<5km v >5km)', 'Big buffer (<5km v >20km)', 'Confirmed & probable cases', 'Units w at least one dengue case')),
                         c('No PM', 'No LUC', 'Pop weight','1km','10km',
                           'No buffer', 'Big buffer', 'Conf & prob cases', 'Units w dengue'))

# Define model colors
model_colors_fill <- c('No PM'='darkred', 'No LUC' = '#DC267F', 'Pop weight'="#FE6100",
                       '1km'='#FFB000','10km'='#FFE518','No buffer'='#85CE76',
                       'Big buffer'='#126E29','Conf & prob cases'="#648FFF",
                       'Units w dengue'="#785EF0", 'Main' = "grey")

model_colors_line <- c('No PM'='darkred', 'No LUC' = '#DC267F', 'Pop weight'="#FE6100",
                       '1km'='#FFB000','10km'='#FFE518','No buffer'='#85CE76',
                       'Big buffer'='#126E29','Conf & prob cases'="#648FFF",
                       'Units w dengue'="#785EF0", 'Main' = "black")

# Plot
sfig3 <- ggplot(facet_df, aes(x = year, y = estimate, group = Model)) +
  geom_hline(yintercept=0, colour='black', linewidth=.4) +
  geom_vline(xintercept=as.Date("2008-01-01"), linetype='dashed', linewidth=0.4) +
  geom_point(aes(x=as.Date("2008-01-01"), y=0, fill=Model), size=3, shape=21, alpha=0.05) +
  geom_point(aes(fill=Model), shape=21, color="black", size=3, alpha=0.6) +
  geom_errorbar(aes(ymin=lower, ymax=upper, color=Model), width=0.1, linewidth=0.5, alpha=0.8) +
  facet_wrap(~Facet, ncol = 3, labeller = labeller(Facet = facet_labels)) +
  scale_color_manual(values = model_colors_line) +
  scale_fill_manual(values = model_colors_fill) +
  scale_y_continuous(trans = scales::pseudo_log_trans(sigma = 4), 
                     limits = c(-13, 70),
                     breaks = c(-10, 0, 10, 20, 40)) +
  xlab("Year") + ylab("change in\ndengue\nincidence\nper 1,000\nrelative\nto 2008") +
  theme_minimal() +
  theme(legend.position = "none",
        strip.text = element_text(size = 12, face = "bold", hjust = 0),
        axis.title.y = element_text(size = 12)) +
  theme_stor

ggsave("SFig3.pdf", plot = sfig3, 
       path = "~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/", 
       width = 13, height = 9, units = "in", device = "pdf")
```

```{r, SFig S4}
#####################
## SFig 4
#####################
# Construct the dataframe
sfig4_df <- rbind(
  as.data.frame(cbind(dengue_yearly_model_2007$coeftable[1:22,], Model = rep("A) Paving in 2007", 22))),
  as.data.frame(cbind(dengue_yearly_model_2008$coeftable[1:22,], Model = rep("B) Paving in 2008", 22))),
  as.data.frame(cbind(dengue_yearly_model$coeftable[1:22,], Model = rep("C) Paving in 2009 (main model)", 22)))
)

# Clean and format
colnames(sfig4_df) <- c("estimate", "std_error", "t_value", "p_value", "Model")
sfig4_df$year <- as.Date(sub("year::(.*):fivekm", "\\1", rownames(sfig4_df)))

sfig4_df$estimate <- as.numeric(sfig4_df$estimate)
sfig4_df$std_error <- as.numeric(sfig4_df$std_error)
sfig4_df$upper <- sfig4_df$estimate + 1.96 * sfig4_df$std_error
sfig4_df$lower <- sfig4_df$estimate - 1.96 * sfig4_df$std_error
sfig4_df$Model <- factor(sfig4_df$Model, levels = c("A) Paving in 2007", "B) Paving in 2008", "C) Paving in 2009 (main model)"))

facet_refs <- data.frame(
  Model = c("A) Paving in 2007", "B) Paving in 2008", "C) Paving in 2009 (main model)"),
  ref_date = as.Date(c("2006-01-01", "2007-01-01", "2008-01-01")),
  ref_y = 0  # y-location for optional highlight point
)

# Plot
sfig4 <- ggplot(sfig4_df, aes(x = year, y = estimate)) +
  geom_hline(yintercept = 0, color = 'grey40', linewidth = 0.4) +

  # Add facet-specific vertical line
  geom_vline(data = facet_refs, aes(xintercept = ref_date), 
             linetype = 'dashed', linewidth = 0.4, inherit.aes = FALSE) +

  # Optional: highlight a reference point at y = 0
  geom_point(data = facet_refs, aes(x = ref_date, y = ref_y), 
             shape = 21, fill = "white", size = 3, inherit.aes = FALSE) +

  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.1, linewidth = 0.5, alpha = 0.8) +
  geom_point(shape = 21, size = 3, fill = 'white') +
  
  facet_wrap(~Model, ncol = 1) +
  xlab("Year") +
  ylab("change in\ndengue\nincidence\nper 1,000\nrelative to\npaving year") +
  scale_y_continuous(trans = scales::pseudo_log_trans(sigma = 4),
                     limits = c(-13, 60)) +
  scale_x_date(date_breaks = "2 year", date_labels = "%Y") +
  theme_minimal() +
  theme_stor +
  theme(strip.text = element_text(size = 12, face = "bold", hjust = 0),
        axis.title.y = element_text(size = 12),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 11))
sfig4

ggsave("SFig4.pdf", plot=sfig4, "~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/", width = 6, height = 8, units = c("in"), device="pdf")
```

```{r, SFig S5}
#####################
## SFig 5a
#####################
dengue_yearly_model_agg_effect_est <- coeftable(dengue_yearly_agg_model)[5,1]

sfig5a <- ggplot() +
  geom_histogram(aes(permuted_effects_stor_full), binwidth = 0.05, fill="grey") +
  geom_vline(xintercept=dengue_yearly_model_agg_effect_est, color='red') +
  xlab("Bootstrapped effect estimate") + ylab("") + 
  theme_bw()+
  theme(plot.title = element_text(hjust=0.5, size=26, face="italic"),
        plot.subtitle = element_text(hjust=0.5, size=22),
        axis.title.y=element_text(size=10,angle=0, vjust=.5, hjust=0.5),
        axis.text.y=element_text(size=10),
        axis.title.x=element_text(size=10),
        axis.text.x=element_text(size=10),
        axis.text = element_text(size=16),
        legend.text=element_text(size=12),
        legend.title=element_text(size=12),
        legend.position = "none",
        strip.text.x = element_text(size = 14))
sfig5a


#####################
## SFig 5b
#####################

sfig5b <- ggplot() +
  geom_histogram(aes(permuted_effects_stor_block), binwidth = 0.05, fill="grey") +
  geom_vline(xintercept=dengue_yearly_model_agg_effect_est, color='red') +
  xlab("Bootstrapped effect estimate") + ylab("") + 
  theme_bw()+
  theme(plot.title = element_text(hjust=0.5, size=26, face="italic"),
        plot.subtitle = element_text(hjust=0.5, size=22),
        axis.title.y=element_text(size=10,angle=0, vjust=.5, hjust=0.5),
        axis.text.y=element_text(size=10),
        axis.title.x=element_text(size=10),
        axis.text.x=element_text(size=10),
        axis.text = element_text(size=16),
        legend.text=element_text(size=12),
        legend.title=element_text(size=12),
        legend.position = "none",
        strip.text.x = element_text(size = 14))
sfig5b


#####################
## SFig 5c
#####################

sfig5c <- ggplot() +
  geom_histogram(aes(permuted_effects_stor_within), binwidth = 0.05, fill="grey") +
  geom_vline(xintercept=dengue_yearly_model_agg_effect_est, color='red') +
  xlab("Bootstrapped effect estimate") + ylab("") + 
  theme_bw()+
  theme(plot.title = element_text(hjust=0.5, size=26, face="italic"),
        plot.subtitle = element_text(hjust=0.5, size=22),
        axis.title.y=element_text(size=10,angle=0, vjust=.5, hjust=0.5),
        axis.text.y=element_text(size=10),
        axis.title.x=element_text(size=10),
        axis.text.x=element_text(size=10),
        axis.text = element_text(size=16),
        legend.text=element_text(size=12),
        legend.title=element_text(size=12),
        legend.position = "none",
        strip.text.x = element_text(size = 14))
sfig5c

#####################
## SFig 5all
#####################

sfig5all <- grid.arrange(sfig5a, sfig5b, sfig5c,
                         nrow = 1)

sfig5all <- as_ggplot(sfig5all) +                                
  draw_plot_label(label = c("A", "B","C"), size = 13,
                  x = c(0.038, 0.371, 0.705), y = c(0.98, 0.98, 0.98)) 
sfig5all

ggsave("sfig5.pdf", plot=sfig5all, path="~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/", width = 12, height = 5, units="in", device = "pdf")

```

```{r, SFig S6}
#####################
## SFig 6a
#####################
#population
dengue_df_yearly_pop <- dengue_yearly$connected_buffered %>%
  group_by(year,fivekm) %>%
  summarise(pop_sum = sum(population))

dengue_df_yearly_pop_no_pm <- dengue_yearly$connected_buffered_no_pm %>%
  group_by(year,fivekm) %>%
  summarise(pop_sum = sum(population))
dengue_df_yearly_pop_no_pm$fivekm <- ifelse(dengue_df_yearly_pop_no_pm$fivekm==1,2,0)
dengue_df_yearly_pop_no_pm <- dengue_df_yearly_pop_no_pm[which(dengue_df_yearly_pop_no_pm$fivekm==2),]

dengue_df_yearly_pop <- rbind(dengue_df_yearly_pop, dengue_df_yearly_pop_no_pm)

dengue_df_yearly_pop$fivekm <- as.character(dengue_df_yearly_pop$fivekm)
dengue_df_yearly_pop$year <- as.Date(dengue_df_yearly_pop$year)

sfig6a <- ggplot(dengue_df_yearly_pop) +
  geom_line(aes(x=year, y=pop_sum, color=fivekm)) +
  geom_vline(xintercept=vert_line_date,linetype='dashed') +
  ggtitle("Population") +
  xlab("Year") + ylab("") + 
  scale_color_manual(name = "Exposure", values=c("#648FFF","#E04490", "#FFD218"), labels=c('Far (>10km)', 'Near (<5km)', 'Near no PM (<5km)'),) +
  scale_y_continuous(labels = label_number(suffix = "k", scale = 1e-3)) +
  theme_bw()+
  theme(plot.title = element_text(size=12, face="bold"),
        plot.subtitle = element_text(hjust=0.5, size=22),
        axis.title=element_text(size=14),
        axis.title.y=element_text(size=12,angle=0, vjust=.5, hjust=0.5),
        axis.text.y=element_text(size=10),
        axis.title.x=element_text(size=12),
        axis.text.x=element_text(size=10),
        axis.text = element_text(size=10),
        legend.text=element_text(size=10),
        legend.title=element_text(size=10),
        legend.position = "none",
        strip.text.x = element_text(size = 10))
sfig6a

#####################
## SFig 6b
#####################
#urban area
dengue_df_yearly_urban <- dengue_yearly$connected_buffered %>%
  group_by(year,fivekm) %>%
  summarise(urban_sum = sum(urban))

dengue_df_yearly_urban_no_pm <- dengue_yearly$connected_buffered_no_pm %>%
  group_by(year,fivekm) %>%
  summarise(urban_sum = sum(urban))
dengue_df_yearly_urban_no_pm$fivekm <- ifelse(dengue_df_yearly_urban_no_pm$fivekm==1,2,0)
dengue_df_yearly_urban_no_pm <- dengue_df_yearly_urban_no_pm[which(dengue_df_yearly_urban_no_pm$fivekm==2),]

dengue_df_yearly_urban <- rbind(dengue_df_yearly_urban, dengue_df_yearly_urban_no_pm)

dengue_df_yearly_urban$fivekm <- as.character(dengue_df_yearly_urban$fivekm)
dengue_df_yearly_urban$year <- as.Date(dengue_df_yearly_urban$year)

sfig6b <- ggplot(dengue_df_yearly_urban) +
  geom_line(aes(x=year, y=urban_sum, color=fivekm)) +
  geom_vline(xintercept=vert_line_date,linetype='dashed') +
  ggtitle("Urban Area (m^2)") +
  xlab("Year") + ylab("") + 
  scale_color_manual(name = "Exposure", values=c("#648FFF","#E04490", "#FFD218"), labels=c('Far (>10km)', 'Near (<5km)', 'Near no PM (<5km)'),) +
  theme_bw()+
  theme(plot.title = element_text(size=12, face="bold"),
        plot.subtitle = element_text(hjust=0.5, size=22),
        axis.title=element_text(size=14),
        axis.title.y=element_text(size=12,angle=0, vjust=.5, hjust=0.5),
        axis.text.y=element_text(size=13),
        axis.title.x=element_text(size=12),
        axis.text.x=element_text(size=10),
        axis.text = element_text(size=10),
        legend.text=element_text(size=10),
        legend.title=element_text(size=10),
        legend.position = "none",
        strip.text.x = element_text(size = 10))
sfig6b

#####################
## SFig 6c
#####################
#agricultural area
dengue_df_yearly_ag <- dengue_yearly$connected_buffered %>%
  group_by(year,fivekm) %>%
  summarise(ag_sum = sum(ag))

dengue_df_yearly_ag_no_pm <- dengue_yearly$connected_buffered_no_pm %>%
  group_by(year,fivekm) %>%
  summarise(ag_sum = sum(ag))
dengue_df_yearly_ag_no_pm$fivekm <- ifelse(dengue_df_yearly_ag_no_pm$fivekm==1,2,0)
dengue_df_yearly_ag_no_pm <- dengue_df_yearly_ag_no_pm[which(dengue_df_yearly_ag_no_pm$fivekm==2),]

dengue_df_yearly_ag <- rbind(dengue_df_yearly_ag, dengue_df_yearly_ag_no_pm)

dengue_df_yearly_ag$fivekm <- as.character(dengue_df_yearly_ag$fivekm)
dengue_df_yearly_ag$year <- as.Date(dengue_df_yearly_ag$year)

sfig6c <- ggplot(dengue_df_yearly_ag) +
  geom_line(aes(x=year, y=ag_sum, color=fivekm)) +
  geom_vline(xintercept=vert_line_date,linetype='dashed') +
  ggtitle("Agricultural Area (m^2)") +
  xlab("Year") + ylab("") + 
  scale_color_manual(name = "Exposure", values=c("#648FFF","#E04490", "#FFD218"), labels=c('Far (>10km)', 'Near (<5km)', 'Near no PM (<5km)'),) +
  theme_bw()+
  theme(plot.title = element_text(size=12, face="bold"),
        plot.subtitle = element_text(hjust=0.5, size=22),
        axis.title=element_text(size=14),
        axis.title.y=element_text(size=12,angle=0, vjust=.5, hjust=0.5),
        axis.text.y=element_text(size=10),
        axis.title.x=element_text(size=12),
        axis.text.x=element_text(size=10),
        axis.text = element_text(size=10),
        legend.text=element_text(size=10),
        legend.title=element_text(size=10),
        legend.position = "bottom",
        strip.text.x = element_text(size = 10))
sfig6c
sfig6_legend <- get_legend(sfig6c)
sfig6c <- sfig6c + theme(legend.position = "none")

#####################
## SFig 6all
#####################

sfig6all <- grid.arrange(sfig6a, sfig6b, sfig6c, sfig6_legend,
                         ncol = 1, nrow = 4,
                         layout_matrix = rbind(c(1),c(2),c(3),c(4)), 
                         heights=c(4,4,4,1))

sfig6all <- as_ggplot(sfig6all) +                                
  draw_plot_label(label = c("A)", "B)", "C)"), size = 14,
                  x = c(0.02, 0.02, 0.02), y = c(1, 0.692, 0.385)) 
sfig6all

ggsave("sfig6.pdf", plot=sfig6all, path="~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/", width = 6, height = 10, units="in", device = "pdf")

```

```{r, SFig S7}
#####################
## SFig 7
#####################

linked_ids_codes <- read.csv("~/Desktop/doctorate/ch2 mdd highway/data/key_esalud_clusterid_7.5km.csv")

center_lat_long <- data.frame(linked_ids_codes)
center_lat_long <- center_lat_long %>%
  mutate(latitude= as.numeric(latitude),longitude= as.numeric(longitude)) %>%
  sf::st_as_sf(coords = c('longitude','latitude'), crs = st_crs(4326))

districts <- read_sf("~/Desktop/doctorate/ch2 mdd highway/data/shapefiles/Madre_de_Dios.shp")
districts <- st_as_sf(districts) 
districts$geometry <- st_transform(districts$geometry, 4326)
mdd_region <- st_union(districts$geometry)

rivers <- read_sf("~/Desktop/doctorate/ch2 mdd highway/data/shapefiles/mdd_rivers2.shp")
rivers <- st_as_sf(rivers, crs=4326) 
rivers$geometry <- st_transform(rivers$geometry, "EPSG:4326")

roads <- read_sf("~/Desktop/doctorate/ch2 mdd highway/data/shapefiles/mdd_roads.shp")
roads <- st_as_sf(roads) 
roads$geometry <- st_transform(roads$geometry, 4326)
roads_mdd <- st_covers(mdd_region,roads$geometry, sparse = FALSE)
roads_mdd <- roads[roads_mdd[1,],]

highway <- read_sf("~/Desktop/doctorate/ch2 mdd highway/data/shapefiles/peru_roads_important.shp")
highway <- highway[which(highway$ref=="PE-30C"),]
highway <- st_as_sf(highway) 
highway$geometry <- st_transform(highway$geometry, 4326)

highway_mdd <- st_covers(mdd_region,highway$geometry, sparse = FALSE)
highway_mdd <- highway[highway_mdd[1,],]

no_axis <- theme(axis.title=element_blank(),
                 axis.text=element_blank(),
                 axis.ticks=element_blank(),
                 panel.grid.major = element_blank())

cluster_sizes <- center_lat_long %>%
  group_by(clust) %>%
  summarise(n_keys = n(), .groups = "drop") %>%
  filter(n_keys > 1)  # Keep only clusters with >1 key

allFeatsCircleCentroid <- read_sf("~/Desktop/doctorate/ch2 mdd highway/data/spatial_units/buffer_7.5km/clusterCentroids_7.5km.shp")
allFeatsCircleCentroid <- allFeatsCircleCentroid %>%
  st_transform(crs=4326)
allFeatsCircleCentroid_filtered <- allFeatsCircleCentroid %>%
  filter(clust %in% cluster_sizes$clust)
# Project to a metric CRS (e.g., UTM Zone 19S for Peru/Brazil)
centroid_proj <- allFeatsCircleCentroid_filtered %>%
  st_transform(crs = 32719)  # EPSG:32719 is UTM Zone 19S (meters)

# Create 7.5km (7500 meter) buffer around each point
buffer_circles <- centroid_proj %>%
  st_buffer(dist = 7500) %>%
  st_transform(crs = 4326)  # Back to lat/lon for plotting

center_lat_long <- center_lat_long %>%
  group_by(clust) %>%
  mutate(clust_indicator = if_else(n() == 1, 0, 1)) %>%
  ungroup()

singletons <- center_lat_long %>% filter(clust_indicator == 0)
clusters   <- center_lat_long %>% filter(clust_indicator == 1)

sfig7 <- ggplot() +
  geom_sf(data = mdd_region, fill='#ffffff', color='#a6a6a6', size=.15, show.legend = FALSE) +
  geom_sf(data = rivers, aes(geometry = geometry, color='lightblue'), fill='lightblue', linewidth=0.2, show.legend = "line") +
  geom_sf(data = roads_mdd, aes(geometry = geometry, color='#a6a6a6'), linewidth=0.5, show.legend = "line") +
  geom_sf(data = highway_mdd, aes(geometry = geometry, color='black'), linewidth=0.7, show.legend = "line") +
  geom_sf(data = singletons, aes(geometry = geometry), fill = 'white', color='black', pch=21, size = 2, alpha=0.7) +
  geom_sf(data = clusters, aes(geometry = geometry), fill = '#648FFF', color='black', pch=21, size = 2, alpha=0.7) +
  geom_sf(data = buffer_circles, aes(geometry = geometry), color='#E04490', fill=NA, linewidth=0.5) +
  scale_fill_viridis_d(name = "Cluster") +
  scale_color_manual(name = "", values = c('#a6a6a6','black','lightblue'),
                     labels = c('Unpaved Roads','Highway','Rivers')) +
  annotation_scale(location = "bl",height = unit(0.1, "cm")) +
  annotation_north_arrow(location = "tl",style = north_arrow_orienteering(text_size = 6), 
                         height = unit(0.7, "cm"), width = unit(0.7, "cm")) +
  theme_minimal() +
  no_axis +
  theme(legend.text = element_text(size=12),
        legend.title = element_text(size=14),
        legend.position = 'bottom') +
  guides(fill = guide_legend(override.aes = list(shape=21)))+
  annotate("segment", 
           x = label_x-0.02, y = label_y, 
           xend = arrow_x, yend = arrow_y,
           arrow = arrow(length = unit(0.17, "cm")), 
           color = "black") +
  annotate("text", 
           x = label_x, y = label_y, 
           label = "PM", 
           size = 3.4, fontface = "bold", hjust = 0, color = "black")
sfig7


buffer_circles_smaller <- centroid_proj %>%
  st_buffer(dist = 4700) %>%
  st_transform(crs = 4326)  # Back to lat/lon for plotting
sfig7a <- ggplot() +
  geom_sf(data = mdd_region, fill='#ffffff', color='#a6a6a6', size=.15, show.legend = FALSE) +
  geom_sf(data = rivers, aes(geometry = geometry, color='lightblue'), fill='lightblue', linewidth=0.2, show.legend = "line") +
  geom_sf(data = roads_mdd, aes(geometry = geometry, color='#a6a6a6'), linewidth=0.5, show.legend = "line") +
  geom_sf(data = highway_mdd, aes(geometry = geometry, color='black'), linewidth=0.7, show.legend = "line") +
  geom_sf(data = singletons, aes(geometry = geometry), fill = 'white', color='black', pch=21, size = 2, alpha=0.7) +
  geom_sf(data = clusters, aes(geometry = geometry), fill = '#648FFF', color='black', pch=21, size = 2, alpha=0.7) +
  geom_sf(data = buffer_circles_smaller, aes(geometry = geometry), color='#E04490', fill=NA, linewidth=0.5) +
  scale_fill_viridis_d(name = "Cluster") +
  scale_color_manual(name = "", values = c('#a6a6a6','black','lightblue'),
                     labels = c('Unpaved Roads','Highway','Rivers')) +
  theme_minimal() +
  no_axis +
  theme(legend.text = element_text(size=12),
        legend.title = element_text(size=14),
        legend.position = 'bottom') +
  guides(fill = guide_legend(override.aes = list(shape=21)))

xlim_pm <- c(-69.30, -69.07)
ylim_pm <- c(-12.83, -12.45)

sfig7_pm <- sfig7a +
  coord_sf(xlim = xlim_pm, ylim = ylim_pm, expand = FALSE) +
  theme(legend.text = element_text(size=12),
        legend.title = element_text(size=14),
        legend.position = 'none')+
  annotation_scale(location = "br",height = unit(0.1, "cm"))
sfig7_pm

sfig7all <- sfig7 + plot_spacer() + sfig7_pm +
  plot_layout(ncol = 3, widths = c(2.5, 0.05, 0.8)) + 
  plot_annotation(
    tag_levels = 'A',
    tag_prefix = '', tag_suffix = '',
    theme = theme(
      plot.tag = element_text(size = 18, face = "bold", hjust = -0.1, vjust = 1.2)
    )
  )

sfig7all

ggsave("SFig7.pdf", plot=sfig7all, "~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/", width = 8, height = 5, units = c("in"), device="pdf")
```

```{r, SFig S8}
#Madre de Dios Traffic Data, compare to Loreto

# Load and reshape all datasets
reshape_traffic_data <- function(df, name) {
  df <- df %>%
    rename_with(~ as.character(.), -1)  # make sure all column names are characters

  # Force all year columns to numeric
  year_cols <- setdiff(colnames(df), "Department")
  df[year_cols] <- lapply(df[year_cols], function(x) as.numeric(as.character(x)))

  df %>%
    pivot_longer(-Department, names_to = "Year", values_to = "Value") %>%
    mutate(
      Year = as.integer(Year),
      Metric = name
    )
}

# Interprovincial Passenger Traffic
interprovincial_passenger_traffic <- read_excel("~/Desktop/doctorate/ch2 mdd highway/data/MTC_traffic_data/TRÁFICO_DE_PASAJEROS_EN_EL_TRANSPORTE_INTERPROVINCIAL.xlsx") %>% 
  filter(`TRÁFICO DE PASAJEROS EN EL TRANSPORTE INTERPROVINCIAL, SEGÚN DEPARTAMENTO DESTINO: 2007-2018` %in% c("Madre de Dios", "Loreto"))
colnames(interprovincial_passenger_traffic) <- c("Department", as.character(2007:2018))
interprovincial_passenger_traffic_long <- reshape_traffic_data(interprovincial_passenger_traffic, "Passenger Traffic")

# Estimated Vehicle Fleet
estimated_vehicle_fleet <- read_excel("~/Desktop/doctorate/ch2 mdd highway/data/MTC_traffic_data/PARQUE_VEHICULAR_ESTIMADO.xlsx") %>% 
  filter(`PARQUE VEHICULAR ESTIMADO, SEGÚN DEPARTAMENTO: 2007-2018` %in% c("Madre de Dios", "Loreto"))
colnames(estimated_vehicle_fleet) <- c("Department", as.character(2007:2018))
estimated_vehicle_fleet_long <- reshape_traffic_data(estimated_vehicle_fleet, "Estimated Vehicle Fleet")

# National Cargo Vehicle Fleet
vehicle_fleet_for_national_cargo <- read_excel("~/Desktop/doctorate/ch2 mdd highway/data/MTC_traffic_data/PARQUE_VEHICULAR_AUTORIZADO_DEL_TRANSPORTE_DE_CARGA_GENERAL_NACIONAL.xlsx") %>% 
  filter(`PARQUE VEHICULAR AUTORIZADO DEL TRANSPORTE DE CARGA GENERAL NACIONAL, SEGÚN DEPARTAMENTO: 2007-2018` %in% c("Madre de Dios", "Loreto"))
colnames(vehicle_fleet_for_national_cargo) <- c("Department", as.character(2007:2018))
vehicle_fleet_national_cargo_long <- reshape_traffic_data(vehicle_fleet_for_national_cargo, "National Cargo Vehicle Fleet")

# Toll Unit Flow
vehicular_flow_at_toll_units <- read_excel("~/Desktop/doctorate/ch2 mdd highway/data/MTC_traffic_data/FLUJO_VEHICULAR_EN_LAS_UNIDADES_DE_PEAJE.xlsx") %>% 
  filter(`FLUJO VEHICULAR EN LAS UNIDADES DE PEAJE, SEGÚN DEPARTAMENTO: 2009-2018` %in% c("Madre de Dios", "Loreto"))
colnames(vehicular_flow_at_toll_units) <- c("Department", as.character(2009:2018))
vehicular_flow_toll_units_long <- reshape_traffic_data(vehicular_flow_at_toll_units, "Toll Unit Flow")

# Combine all long-form datasets
all_traffic_data <- bind_rows(
  interprovincial_passenger_traffic_long,
  estimated_vehicle_fleet_long,
  vehicle_fleet_national_cargo_long,
  vehicular_flow_toll_units_long
)

desired_order <- c(
  "Passenger Traffic",
  "Estimated Vehicle Fleet",
  "National Cargo Vehicle Fleet",
  "Toll Unit Flow"
)

labeled_titles <- c(
  "Passenger Traffic" = "A. Passenger Traffic",
  "Estimated Vehicle Fleet" = "B. Estimated Vehicle Fleet (% change)",
  "National Cargo Vehicle Fleet" = "C. National Cargo Vehicle Fleet",
  "Toll Unit Flow" = "D. Toll Unit Flow"
)

percent_change_df <- all_traffic_data %>%
  filter(Metric == "Estimated Vehicle Fleet") %>%
  group_by(Department) %>%
  arrange(Year) %>%
  mutate(Value = 100 * (Value / first(Value) - 1)) %>%
  ungroup()

all_traffic_data <- all_traffic_data %>%
  filter(Metric != "Estimated Vehicle Fleet") %>%
  bind_rows(percent_change_df) %>%
  # mutate(Value = ifelse(Value == 0, NA, Value)) %>%
  mutate(Metric = factor(Metric, levels = desired_order))


sfig8 <- ggplot(all_traffic_data, aes(x = Year, y = Value, color = Department)) +
  geom_line(size = 1) +
  geom_vline(xintercept = 2008, linetype = "dashed", color = "black", linewidth = 0.7) +
  facet_wrap(~Metric, scales = "free_y", ncol = 2,
             labeller = as_labeller(labeled_titles)) +
  labs(x = "Year",
       y = "",
       color = "Department") +
  scale_color_manual(values = c("Madre de Dios" = "#E04490",
                                "Loreto" = "#648FFF")) +
  theme_minimal(base_size = 14) +
  theme_stor +
  theme(strip.text = element_text(face = "bold", hjust = 0),
        legend.position = "bottom")
sfig8

ggsave("SFig8.pdf", plot=sfig8, path="~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/", width = 9, height = 7, units="in", device = "pdf")
```

```{r, SFig S9}
#####################
## SFig 9a
#####################
### precip data
precip_monthly <- read.csv("~/Desktop/doctorate/ch2 mdd highway/data/covariates_data_7.5km/mdd_precipitation_monthly_sum.csv")
precip_monthly <- precip_monthly[,c(2:278)]
precip_monthly <- precip_monthly[,c(277,1:276)]
colnames(precip_monthly)[2:277] <- as.character(seq(as.Date("2000-01-01"), as.Date("2022-12-01"), by="months"))
colnames(precip_monthly)[1] <- "key"
precip_monthly_mdd_long <- precip_monthly %>%
  pivot_longer(cols = c(2:277), 
               names_to = "month", 
               values_to = "sum_precip")
precip_monthly_mdd_long$year <- format(as.Date(precip_monthly_mdd_long$month, format="%Y-%m-%d"),"%Y")

#look at precip to inform rainy season/biannual split
precip_monthly_mdd_long$year <- format(as.Date(precip_monthly_mdd_long$month, format="%Y-%m-%d"),"%Y")
precip_monthly_all <- precip_monthly_mdd_long %>%
  group_by(month, year) %>%
  summarize(sum_precip = sum(sum_precip)) 
precip_monthly_all$month_wo_year <- format(as.Date(precip_monthly_all$month, format="%Y-%m-%d"),"%m")
sfig9a <- ggplot(precip_monthly_all) +
  geom_line(aes(x=month_wo_year,y=sum_precip,group=year), color="black", alpha=0.7) +
  geom_hline(yintercept=mean(precip_monthly_all$sum_precip), color='red', linetype="dashed") +
  geom_vline(xintercept=04, color='red', linetype="dashed") +
  geom_vline(xintercept=10, color='red', linetype="dashed") +
  xlab("Month") + ylab("Acc.\nmonthly\nprecip") + 
  theme_bw()+
  theme(plot.title = element_text(hjust=0.5, size=26, face="italic"),
        plot.subtitle = element_text(hjust=0.5, size=22),
        axis.title.y=element_text(size=10,angle=0, vjust=.5, hjust=0.5),
        axis.text.y=element_text(size=10),
        axis.title.x=element_text(size=10),
        axis.text.x=element_text(size=10, angle=45, vjust=0.45),
        axis.text = element_text(size=16),
        legend.text=element_text(size=12),
        legend.title=element_text(size=12),
        legend.position = "none",
        strip.text.x = element_text(size = 14))
sfig9a

#####################
## SFig 9b
#####################
dengue_monthly <- read.csv("~/Desktop/doctorate/ch2 mdd highway/data/processed_case_data_0km/dengue_monthly_full_dataset_c.csv")
dengue_monthly <- dengue_monthly %>%
  group_by(month, year) %>%
  summarize(mean_cases = mean(monthly_cases))
dengue_monthly$month_wo_year <- format(as.Date(dengue_monthly$month, format="%Y-%m-%d"),"%m")
dengue_monthly$year_wo_month <- format(as.Date(dengue_monthly$month, format="%Y-%m-%d"),"%Y")

sfig9b <- ggplot(dengue_monthly) +
  geom_line(aes(x=month_wo_year,y=mean_cases,group=year), color='black', alpha=0.7) +
  #geom_hline(yintercept=mean(dengue_monthly$mean_cases), color='red', linetype="dashed") +
  geom_vline(xintercept=04, color='red', linetype="dashed") +
  geom_vline(xintercept=10, color='red', linetype="dashed") +
  xlab("Month") + ylab("Mean\nmonthly\ndengue\ncases") + 
  theme_bw()+
  theme(plot.title = element_text(hjust=0.5, size=26, face="italic"),
        plot.subtitle = element_text(hjust=0.5, size=22),
        axis.title.y=element_text(size=10,angle=0, vjust=.5, hjust=0.5),
        axis.text.y=element_text(size=10),
        axis.title.x=element_text(size=10),
        axis.text.x=element_text(size=10, angle=45, vjust=0.45),
        axis.text = element_text(size=16),
        legend.text=element_text(size=12),
        legend.title=element_text(size=12),
        legend.position = "none",
        strip.text.x = element_text(size = 14)) +
  geom_text_repel(
    data = subset(dengue_monthly, (month_wo_year == 12 & year_wo_month %in% c('2019','2022','2010','2020','2012','2009','2013','2015'))),
    aes(x = month_wo_year, y = mean_cases, label = year_wo_month), 
    color='slategrey',
    point.size = NA,
    min.segment.length = 0,
    size = 2.5,
    hjust = 'right',
    direction = "y",
    nudge_x = 0.8,
    segment.color = 'slategrey',
    segment.alpha = 0.7,
    #segment.curvature = -0.1,
    #segment.ncp = 3,
    #segment.angle = 20,
    point.padding = 0.1,
    show.legend = FALSE,
    angle = 0,
    arrow = arrow(length = unit(0.01, "npc")),
    expand = expansion(mult = 0.4)
  )
sfig9b

#####################
## SFig 9all
#####################
sfig9all <- grid.arrange(sfig9a, sfig9b,
                         ncol = 1, nrow = 2,
                         layout_matrix = rbind(c(1),c(2)), 
                         heights=c(1,1))

sfig9all <- as_ggplot(sfig9all) +                                
  draw_plot_label(label = c("A", "B"), size = 14,
                  x = c(0.11, 0.11), y = c(0.99, 0.49)) 
sfig9all

ggsave("SFig9.pdf", plot=sfig9all, path="~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/", width = 8, height = 8, units="in", device = "pdf")
```

```{r, SFig S10}
y_lims_biannual <- c(-7,50)

#dengue
df <- as.data.frame(dengue_biannual_model$coeftable)
df <- df[1:45,]
colnames(df) <- c('estimate', 'std_error', 't_value', 'p_value')
df$biannual_date <- as.Date(c(unique(dengue_df_biannual$biannual_date)[c(1:16,18:46)]))
df$rainy <- 0
df$rainy[c(seq(2, 16, 2), seq(17, 45, 2))] <- 1
df$rainy <- as.character(df$rainy)
df$upper <- df$estimate+1.96*df$std_error
df$lower <- df$estimate-1.96*df$std_error
sfig10a <- ggplot(df) +
  geom_hline(aes(yintercept=0), colour='red', size=.4) +
  geom_errorbar(aes(x=biannual_date, ymax=upper, ymin=lower, colour=rainy), width=0, size=0.5) +
  geom_vline(aes(xintercept=as.Date("2008-04-01")), linetype='dashed', size=0.4) +
  geom_point(aes(x=as.Date("2008-04-01"), y=0), size=3, shape=21, fill='white') +
  geom_point(aes(biannual_date, estimate, fill=rainy), size=3, shape=21) +
  scale_fill_manual(name="Season", values=c('#DC267F', '#648FFF'), labels=c('Dry', 'Rainy')) + 
  scale_colour_manual(name="Season", values=c('#DC267F', '#648FFF'), labels=c('Dry', 'Rainy')) + 
  xlab("Biannual time period") + ylab("change in\ndengue\nincidence\nper 1,000\nrelative\nto 2008") + 
  theme_minimal()+
  scale_y_continuous(trans = scales::pseudo_log_trans(sigma = 4),
                     limits = y_lims_biannual) +
  theme_stor +
  theme(legend.position = "bottom")
sfig10a
sfig10_legend <- get_legend(sfig10a)
sfig10a <- sfig10a + theme(legend.position = "none")

###leish

df <- as.data.frame(leish_biannual_model$coeftable)
df <- df[1:45,]
colnames(df) <- c('estimate', 'std_error', 't_value', 'p_value')
df$biannual_date <- as.Date(c(unique(leish_df_biannual$biannual_date)[c(1:16,18:46)]))
df$rainy <- 0
df$rainy[c(seq(2, 16, 2), seq(17, 45, 2))] <- 1
df$rainy <- as.character(df$rainy)
df$upper <- df$estimate+1.96*df$std_error
df$lower <- df$estimate-1.96*df$std_error
sfig10b <- ggplot(df) +
  geom_hline(aes(yintercept=0), colour='red', size=.4) +
  geom_errorbar(aes(x=biannual_date, ymax=upper, ymin=lower, colour=rainy), width=0, size=0.5) +
  geom_vline(aes(xintercept=as.Date("2008-04-01")), linetype='dashed', size=0.4) +
  geom_point(aes(x=as.Date("2008-04-01"), y=0), size=3, shape=21, fill='white') +
  geom_point(aes(biannual_date, estimate, fill=rainy), size=3, shape=21) +
  scale_fill_manual(name="Season", values=c('#DC267F', '#648FFF'), labels=c('Dry', 'Rainy')) + 
  scale_colour_manual(name="Season", values=c('#DC267F', '#648FFF'), labels=c('Dry', 'Rainy')) + 
  xlab("Biannual time period") + ylab("change in\nleish\nincidence\nper 1,000\nrelative\nto 2008") + 
  theme_minimal()+
  scale_y_continuous(trans = scales::pseudo_log_trans(sigma = 4),
                     limits = y_lims_biannual) +
  theme_stor

sfig10b

#####################
## SFig 10all
#####################

sfig10all <- grid.arrange(sfig10a, sfig10b, sfig10_legend,
                         ncol = 1, nrow = 3,
                         layout_matrix = rbind(c(1),c(2),c(3)), 
                         heights=c(5,5,1))

sfig10all <- as_ggplot(sfig10all) +                                
  draw_plot_label(label = c("A", "B"), size = 14,
                  x = c(0.14, 0.14), y = c(0.99, 0.535)) 
sfig10all

ggsave("sfig10.pdf", plot=sfig10all, path="~/Desktop/doctorate/ch2 mdd highway/supplementary_figures/", width = 8, height = 11, units="in", device = "pdf")
```










